-- Add new columns to products table
ALTER TABLE products
ADD COLUMN IF NOT EXISTS category VARCHAR(255),
ADD COLUMN IF NOT EXISTS material VARCHAR(255),
ADD COLUMN IF NOT EXISTS department VARCHAR(255),
ADD COLUMN IF NOT EXISTS gallery TEXT,
ADD COLUMN IF NOT EXISTS "hasDiscount" BOOLEAN,
ADD COLUMN IF NOT EXISTS "discountValue" DECIMAL(5,2),
ADD COLUMN IF NOT EXISTS stock INTEGER DEFAULT 0;
